spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ''
    username: ''
    password: ''
    tomcat:
      test-while-idle: true
      validation-query: SELECT 1
  flyway:
    baseline-on-migrate: true
    enabled: true
    locations: classpath:db/migration
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: SGCP
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
        show_sql: true
        temp:
          use_jdbc_metadata_defaults: false
        type: info
        use_sql_comments: true
        
logging:
  pattern:
    console: '%d{dd/MM/yyyy HH:mm:ss} - %-5level - %msg%n'

jwt:
  expiration: 86400000 #duração de 1 dias
  secret: ''