spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      
server:
  servlet:
    context-path: /sgcp      

aws:
  access_key_id: ''
  secret_access_key: ''
  
img:
  prefix:
    client:
      profile: cp
  profile:
    size: 200
    
mail:
  username: ''
  password: ''
  smtp:
    auth: true
    debug: true
    from: ''
    host: smtp.googlemail.com
    port: 465
    socketFactory:
      class: javax.net.ssl.SSLSocketFactory
      fallback: false
      port: 465
    ssl:
      enable: true
    starttls:
      enable: true
      required: true
  test-connection: true
  transport:
    protocol: smtp  
  
s3:
  bucket: caderneta-conta
  region: sa-east-1
    

