server:
  servlet:
    context-path: /sgcp

spring:
  profiles:
    active: ${ENVIRONMENT}
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB  
  datasource:
    url: ${DATABASE_URL}
    driver-class-name: org.postgresql.Driver
    initialization-mode: never
    tomcat:
      test-while-idle: true
      validation-query: SELECT 1   
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: none    properties:      hibernate:
        default_schema: ${DATABASE_SCHEMA}
        dialect: org.hibernate.dialect.PostgreSQLDialect 
        jdbc:
          lob:
            non_contextual_creation: true
          temp:
            use_jdbc_metadata_defaults: false

database:
  user: ${DATABASE_USER}
  pass: ${DATABASE_PASS}

aws:
  access_key_id: ${S3_KEY}
  secret_access_key: ${S3_SECRET}
  s3:
    bucket: caderneta-conta
    region: sa-east-1
  
img:
  prefix:
    client:
      profile: cp
  profile:
    size: 200
    
mail:
  username: ${EMAIL_USER}
  password: ${EMAIL_PASS}
  smtp:
    auth: true
    debug: true
    from: ${EMAIL_USER}
    host: smtp.googlemail.com
    port: 465
    socketFactory:
      class: javax.net.ssl.SSLSocketFactory
      fallback: false
      port: 465
    ssl:
      enable: true
    starttls:
      enable: true
      required: true
  test-connection: true
  transport:
    protocol: smtp
        
jwt:
  expiration: ${JWT_EXPIRATION}
  secret: ${JWT_SECRET}
