-- ADICIONANDO OS MESES
INSERT INTO SGCP.TB_MES(DESC_MES) VALUES ('JANEIRO');
INSERT INTO SGCP.TB_MES(DESC_MES) VALUES ('FEVEREIRO');
INSERT INTO SGCP.TB_MES(DESC_MES) VALUES ('MARÇO');
INSERT INTO SGCP.TB_MES(DESC_MES) VALUES ('ABRIL');
INSERT INTO SGCP.TB_MES(DESC_MES) VALUES ('MAIO');
INSERT INTO SGCP.TB_MES(DESC_MES) VALUES ('JUNHO');
INSERT INTO SGCP.TB_MES(DESC_MES) VALUES ('JULHO');
INSERT INTO SGCP.TB_MES(DESC_MES) VALUES ('AGOSTO');
INSERT INTO SGCP.TB_MES(DESC_MES) VALUES ('SETEMBRO');
INSERT INTO SGCP.TB_MES(DESC_MES) VALUES ('OUTUBRO');
INSERT INTO SGCP.TB_MES(DESC_MES) VALUES ('NOVEMBRO');
INSERT INTO SGCP.TB_MES(DESC_MES) VALUES ('DEZEMBRO');

-- ADICIONANDO OS TIPOS DE CONTAS
INSERT INTO SGCP.TB_TIPO_CONTA (NOME_TIPO_CONTA, DESC_TIPO_CONTA) VALUES ('ALUGUEL', 'ALUGUEL');
INSERT INTO SGCP.TB_TIPO_CONTA (NOME_TIPO_CONTA, DESC_TIPO_CONTA) VALUES ('AGUA', 'ÁGUA');
INSERT INTO SGCP.TB_TIPO_CONTA (NOME_TIPO_CONTA, DESC_TIPO_CONTA) VALUES ('LUZ', 'ENERGIA');
INSERT INTO SGCP.TB_TIPO_CONTA (NOME_TIPO_CONTA, DESC_TIPO_CONTA) VALUES ('GAS', 'GÁS');
INSERT INTO SGCP.TB_TIPO_CONTA (NOME_TIPO_CONTA, DESC_TIPO_CONTA) VALUES ('COMBO', 'TV + INTERNET E/OU TELEFONE FIXO');
INSERT INTO SGCP.TB_TIPO_CONTA (NOME_TIPO_CONTA, DESC_TIPO_CONTA) VALUES ('CC', 'CARTÃO DE CREDITO');
INSERT INTO SGCP.TB_TIPO_CONTA (NOME_TIPO_CONTA, DESC_TIPO_CONTA) VALUES ('CELULAR', 'CELULAR');
INSERT INTO SGCP.TB_TIPO_CONTA (NOME_TIPO_CONTA, DESC_TIPO_CONTA) VALUES ('FINANCIAMANTO IMOBILIARIO', 'FINANCIAMANTO IMOBILIARIO');
INSERT INTO SGCP.TB_TIPO_CONTA (NOME_TIPO_CONTA, DESC_TIPO_CONTA) VALUES ('FINANCIAMANTO AUTOMOTIVO', 'FINANCIAMANTO AUTOMOTIVO');

-- ADICIONANDO O STATUS DA CONTA
INSERT INTO SGCP.TB_STATUS_CONTA(DESCRICAO) VALUES ('A PARGAR');
INSERT INTO SGCP.TB_STATUS_CONTA(DESCRICAO) VALUES ('PAGO');
INSERT INTO SGCP.TB_STATUS_CONTA(DESCRICAO) VALUES ('VENCIDO');
INSERT INTO SGCP.TB_STATUS_CONTA(DESCRICAO) VALUES ('PARCELADO');


INSERT INTO SGCP.TB_USUARIO (NOME, EMAIL, SENHA, FL_ATIVO, DT_CADASTRO) VALUES ('sys', 'sirondba@gmail.com', '$2a$10$vlUpoD3T8/mIaCbE5hDNeOJM1Vrbv8KqHDNPgpoqNUZ9CmeSVPTUm', 'S', NOW());

INSERT INTO SGCP.TB_ROLE VALUES ('ROLE_ADMIN');
INSERT INTO SGCP.TB_ROLE VALUES ('ROLE_USER');

INSERT INTO SGCP.TB_USUARIO_ROLE VALUES (1, 'ROLE_ADMIN');